/* Vibemilk Design System v3.0.0 */
/* Theme: acid-pop */
/* Auto-generated by build-tokens.js -- do not edit */
/* Colors are RGB565 for ESP32 TFT displays */

#ifndef VIBEMILK_ACID_POP_H
#define VIBEMILK_ACID_POP_H

#include <stdint.h>

#define VM_THEME_MODE "'dark'"
#define VM_FONT_FAMILY "'Delius Unicase', 'Chakra Petch', 'Montserrat', -apple-system, BlinkMacSystemFont, sans-serif"
#define VM_FONT_MONO "'Space Mono', 'SF Mono', 'Fira Code', 'Cascadia Code', monospace"
#define VM_FONT_ICONS "'VibemilkIcons', 'Symbols Nerd Font Mono', sans-serif"
#define VM_FS_DISPLAY_XL 38
#define VM_FS_DISPLAY_LG 30
#define VM_FS_HEADING_XL 25
#define VM_FS_HEADING_LG 21
#define VM_FS_HEADING_MD 18
#define VM_FS_HEADING_SM 16
#define VM_FS_BODY_LG 16
#define VM_FS_BODY_MD 14
#define VM_FS_BODY_SM 13
#define VM_FS_CAPTION 12
#define VM_FS_OVERLINE 11
#define VM_FS_MICRO 10
#define VM_FW_LIGHT 300
#define VM_FW_REGULAR 400
#define VM_FW_MEDIUM 500
#define VM_FW_SEMIBOLD 600
#define VM_FW_BOLD 700
#define VM_FW_EXTRABOLD 800
#define VM_BTN_HEIGHT_XS 28
#define VM_BTN_HEIGHT_SM 36
#define VM_BTN_HEIGHT_MD 44
#define VM_BTN_HEIGHT_LG 52
#define VM_BTN_HEIGHT_XL 56
#define VM_BTN_PADDING_XS 10
#define VM_BTN_PADDING_SM 16
#define VM_BTN_PADDING_MD 22
#define VM_BTN_PADDING_LG 28
#define VM_BTN_PADDING_XL 32
#define VM_INPUT_HEIGHT_SM 40
#define VM_INPUT_HEIGHT_MD 46
#define VM_INPUT_HEIGHT_LG 54
#define VM_PROGRESS_HEIGHT 12
#define VM_TOGGLE_TRACK_WIDTH 44
#define VM_TOGGLE_TRACK_HEIGHT 24
#define VM_TOGGLE_THUMB_SIZE 18
#define VM_TOGGLE_THUMB_OFFSET 3
#define VM_AVATAR_SIZE_XS 28
#define VM_AVATAR_SIZE_SM 36
#define VM_AVATAR_SIZE_MD 44
#define VM_AVATAR_SIZE_LG 56
#define VM_AVATAR_SIZE_XL 72
#define VM_BG_DEEPEST 0x0821  /* #08040E */
#define VM_BG_DEEP 0x1043  /* #12081B */
#define VM_BG_SURFACE 0x1886  /* #1D1131 */
#define VM_BG_SURFACE_HOVER 0x20C8  /* #261841 */
#define VM_BG_ELEVATED 0x28C9  /* #2B1A4A */
#define VM_BG_ELEVATED_HOVER 0x310B  /* #34215E */
#define VM_BG_INPUT 0x1044  /* #150A26 */
#define VM_BG_INPUT_FOCUS 0x2087  /* #23103D */
#define VM_BG_OVERLAY "rgba(8, 4, 14, 0.88)"
#define VM_TEXT_PRIMARY 0xFFBF  /* #F9F4FF */
#define VM_TEXT_SECONDARY 0xD63E  /* #D5C6F2 */
#define VM_TEXT_TERTIARY 0xAC7A  /* #A98ED1 */
#define VM_TEXT_MUTED 0x72D1  /* #705B8E */
#define VM_TEXT_INVERSE 0x0842  /* #0F0A16 */
#define VM_TEXT_ON_GRADIENT 0x1044  /* #170A24 */
#define VM_ACCENT_PRIMARY 0xF95A  /* #FF2BD6 */
#define VM_ACCENT_PRIMARY_HOVER 0xFB3C  /* #FF64E5 */
#define VM_ACCENT_PRIMARY_ACTIVE 0xD8B6  /* #D917B5 */
#define VM_ACCENT_PRIMARY_SUBTLE "rgba(255, 43, 214, 0.2)"
#define VM_ACCENT_SECONDARY 0x7FE0  /* #7CFF00 */
#define VM_ACCENT_SECONDARY_HOVER 0xA7E9  /* #A4FF4A */
#define VM_ACCENT_SECONDARY_SUBTLE "rgba(124, 255, 0, 0.22)"
#define VM_COLOR_SUCCESS 0x47F3  /* #46FF9A */
#define VM_COLOR_SUCCESS_HOVER 0x77F6  /* #74FFB5 */
#define VM_COLOR_SUCCESS_SUBTLE "rgba(70, 255, 154, 0.16)"
#define VM_COLOR_WARNING 0xFEAA  /* #FFD553 */
#define VM_COLOR_WARNING_HOVER 0xFF0F  /* #FFE07D */
#define VM_COLOR_WARNING_SUBTLE "rgba(255, 213, 83, 0.16)"
#define VM_COLOR_DANGER 0xFA6F  /* #FF4F7A */
#define VM_COLOR_DANGER_HOVER 0xFBD3  /* #FF7A9B */
#define VM_COLOR_DANGER_SUBTLE "rgba(255, 79, 122, 0.18)"
#define VM_COLOR_INFO 0x2FBF  /* #2CF4FF */
#define VM_COLOR_INFO_SUBTLE "rgba(44, 244, 255, 0.2)"
#define VM_GRADIENT_BRAND "linear-gradient(135deg, #FF2BD6 0%, #7CFF00 100%)"
#define VM_GRADIENT_CARD "linear-gradient(135deg, #FF2BD6 0%, #2CF4FF 100%)"
#define VM_GRADIENT_SUCCESS "linear-gradient(135deg, #46FF9A 0%, #7CFF00 100%)"
#define VM_GRADIENT_WARM "linear-gradient(135deg, #FFE274 0%, #FF4F7A 100%)"
#define VM_GRADIENT_SURFACE "linear-gradient(150deg, #1D1131 0%, #2B1A4A 100%)"
#define VM_GRADIENT_SIDEBAR "linear-gradient(180deg, #1A0D29 0%, #08040E 100%)"
#define VM_GRADIENT_GLOW_PURPLE "radial-gradient(circle, rgba(255, 43, 214, 0.28) 0%, transparent 70%)"
#define VM_GRADIENT_GLOW_BLUE "radial-gradient(circle, rgba(124, 255, 0, 0.2) 0%, transparent 72%)"
#define VM_SPACE_0 0
#define VM_SPACE_1 4
#define VM_SPACE_2 8
#define VM_SPACE_3 12
#define VM_SPACE_4 16
#define VM_SPACE_5 20
#define VM_SPACE_6 24
#define VM_SPACE_8 32
#define VM_SPACE_10 40
#define VM_SPACE_12 48
#define VM_SPACE_16 64
#define VM_PHI_1 4
#define VM_PHI_2 7
#define VM_PHI_3 11
#define VM_PHI_4 18
#define VM_PHI_5 29
#define VM_PHI_6 47
#define VM_PHI_7 76
#define VM_PHI_8 123
#define VM_RADIUS_XS 6
#define VM_RADIUS_SM 10
#define VM_RADIUS_MD 14
#define VM_RADIUS_LG 18
#define VM_RADIUS_XL 24
#define VM_RADIUS_2XL 30
#define VM_RADIUS_FULL 9999
#define VM_SHADOW_SM "0 4px 14px rgba(9, 4, 17, 0.38)"
#define VM_SHADOW_MD "0 10px 24px rgba(9, 4, 17, 0.46)"
#define VM_SHADOW_LG "0 16px 38px rgba(9, 4, 17, 0.54)"
#define VM_SHADOW_XL "0 24px 52px rgba(9, 4, 17, 0.6)"
#define VM_SHADOW_GLOW_SM "0 0 24px rgba(255, 43, 214, 0.26)"
#define VM_SHADOW_GLOW_MD "0 0 36px rgba(124, 255, 0, 0.24)"
#define VM_SHADOW_GLOW_BLUE "0 0 28px rgba(44, 244, 255, 0.24)"
#define VM_SHADOW_INSET "inset 0 0 0 1px rgba(255, 43, 214, 0.22), inset 0 2px 8px rgba(0, 0, 0, 0.32)"
#define VM_STROKE_WIDTH_UI 2
#define VM_STROKE_WIDTH_STRONG 2
#define VM_STROKE_WIDTH_HEAVY 2
#define VM_STROKE_SUBTLE "rgba(255, 43, 214, 0.22)"
#define VM_STROKE_DEFAULT "rgba(255, 43, 214, 0.36)"
#define VM_STROKE_STRONG "rgba(124, 255, 0, 0.56)"
#define VM_STROKE_ACCENT 0xF95A  /* #FF2BD6 */
#define VM_STROKE_SUCCESS 0x47F3  /* #46FF9A */
#define VM_STROKE_DANGER 0xFA6F  /* #FF4F7A */
#define VM_BORDER_SUBTLE "var(--stroke-width-ui) solid var(--stroke-subtle)"
#define VM_BORDER_DEFAULT "var(--stroke-width-ui) solid var(--stroke-default)"
#define VM_BORDER_STRONG "var(--stroke-width-strong) solid var(--stroke-strong)"
#define VM_BORDER_ACCENT "var(--stroke-width-strong) solid var(--stroke-accent)"
#define VM_BORDER_SUCCESS "var(--stroke-width-strong) solid var(--stroke-success)"
#define VM_BORDER_DANGER "var(--stroke-width-strong) solid var(--stroke-danger)"
#define VM_TRANSITION_FAST "150ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_BASE "250ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_SLOW "400ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_SPRING "500ms cubic-bezier(0.34, 1.56, 0.64, 1)"
#define VM_Z_BASE 0
#define VM_Z_RAISED 10
#define VM_Z_DROPDOWN 100
#define VM_Z_STICKY 200
#define VM_Z_OVERLAY 300
#define VM_Z_MODAL 400
#define VM_Z_TOAST 500
#define VM_Z_TOOLTIP 600
#define VM_CONTAINER_SM 640
#define VM_CONTAINER_MD 960
#define VM_CONTAINER_LG 1200
#define VM_CONTAINER_XL 1440
#define VM_SIDEBAR_COLLAPSED 108
#define VM_SIDEBAR_EXPANDED 272
#define VM_TOPBAR_HEIGHT 72
#define VM_SELECTION_BG "rgba(255, 43, 214, 0.36)"
#define VM_SELECTION_TEXT 0x1044  /* #160B22 */
#define VM_SURFACE_OVERLAY_SOFT "rgba(255, 43, 214, 0.08)"
#define VM_SURFACE_OVERLAY_STRONG "rgba(124, 255, 0, 0.3)"
#define VM_CARD_HOVER_BORDER "rgba(124, 255, 0, 0.52)"
#define VM_TABLE_STRIPE_BG "rgba(255, 43, 214, 0.05)"
#define VM_DIVIDER_COLOR "rgba(255, 43, 214, 0.28)"
#define VM_DIVIDER_DASHED_COLOR "rgba(124, 255, 0, 0.3)"
#define VM_SKELETON_SHIMMER "linear-gradient(90deg, transparent, rgba(255, 43, 214, 0.14), transparent)"
#define VM_FOCUS_RING_COLOR "rgba(124, 255, 0, 0.58)"
#define VM_FOCUS_RING_SOFT "0 0 0 3px rgba(124, 255, 0, 0.24)"
#define VM_FOCUS_RING_DANGER "0 0 0 3px rgba(255, 79, 122, 0.28)"
#define VM_SCROLLBAR_TRACK "color-mix(in srgb, var(--bg-deep) 82%, var(--text-primary) 18%)"
#define VM_SCROLLBAR_THUMB "color-mix(in srgb, var(--accent-primary) 54%, var(--text-primary) 46%)"
#define VM_SCROLLBAR_THUMB_HOVER "color-mix(in srgb, var(--accent-primary) 40%, var(--text-primary) 60%)"
#define VM_SCROLLBAR_CORNER "color-mix(in srgb, var(--bg-deep) 72%, var(--bg-elevated) 28%)"
#define VM_SCROLLBAR_DURATION "220ms cubic-bezier(0.22, 1, 0.36, 1)"
#define VM_GUI_PANEL_BG "color-mix(in srgb, var(--bg-elevated) 78%, var(--bg-surface) 22%)"
#define VM_GUI_PANEL_BORDER "1px solid color-mix(in srgb, var(--stroke-default) 70%, var(--text-primary) 30%)"
#define VM_GUI_PANEL_HEADER "color-mix(in srgb, var(--text-primary) 76%, var(--text-secondary) 24%)"
#define VM_GUI_PANEL_SHADOW "var(--shadow-md)"
#define VM_GUI_ROW_GAP "var(--space-4)"
#define VM_GUI_LABEL_COLOR "color-mix(in srgb, var(--text-secondary) 82%, var(--text-primary) 18%)"
#define VM_GUI_VALUE_COLOR "var(--text-primary)"
#define VM_GUI_VALUE_BORDER "1px solid color-mix(in srgb, var(--stroke-default) 74%, var(--text-primary) 26%)"
#define VM_GUI_SLIDER_TRACK "color-mix(in srgb, var(--bg-deep) 45%, var(--text-primary) 55%)"
#define VM_GUI_SLIDER_THUMB "color-mix(in srgb, var(--accent-primary) 68%, var(--text-primary) 32%)"
#define VM_GUI_SLIDER_THUMB_SHADOW "var(--range-thumb-shadow)"
#define VM_GUI_SLIDER_TRANSITION "220ms cubic-bezier(0.22, 1, 0.36, 1)"
#define VM_GRADIENT_TEXT "linear-gradient(90deg, #FF1DA5 0%, #A044C8 55%, #5D3FD3 100%)"
#define VM_TEXT_ON_PRIMARY 0x1044  /* #170A24 */
#define VM_TEXT_ON_SUCCESS 0x08A1  /* #0A170F */
#define VM_TEXT_ON_DANGER 0xFF9E  /* #FFF3F6 */
#define VM_TEXT_ON_WARNING 0x2901  /* #2C2109 */
#define VM_LOADER_STROKE "rgba(249, 244, 255, 0.28)"
#define VM_LOADER_STROKE_ACTIVE 0xFFBF  /* #F9F4FF */
#define VM_CONTROL_HANDLE 0xFFBF  /* #F9F4FF */
#define VM_CONTROL_HANDLE_SHADOW "0 2px 4px rgba(0, 0, 0, 0.34)"
#define VM_RANGE_THUMB_SHADOW "0 2px 6px rgba(0, 0, 0, 0.34)"
#define VM_STATUS_GLOW_SUCCESS "0 0 12px rgba(70, 255, 154, 0.62)"
#define VM_STATUS_GLOW_WARNING "0 0 12px rgba(255, 213, 83, 0.58)"
#define VM_NERDS_BORDER "var(--stroke-width-ui) solid rgba(255, 43, 214, 0.24)"
#define VM_NERDS_INSET_GLOW "inset 0 0 56px rgba(255, 43, 214, 0.06)"
#define VM_NERDS_LABEL 0x7B14  /* #7B63A3 */
#define VM_NERDS_DIVIDER "rgba(124, 255, 0, 0.24)"
#define VM_NERDS_FOOTER_BORDER "var(--stroke-width-ui) solid rgba(124, 255, 0, 0.22)"
#define VM_NERDS_FOOTER_COLOR 0x8355  /* #836AAE */
#define VM_FX_GRID_PERSPECTIVE 620
#define VM_FX_GRID_PLANE_BOTTOM "-7vh"
#define VM_FX_GRID_PLANE_HEIGHT "64vh"
#define VM_FX_GRID_PLANE_SIZE 35
#define VM_FX_GRID_PLANE_OPACITY "0.98"
#define VM_FX_GRID_PLANE_LINE_A "rgba(255, 43, 214, 0.3)"
#define VM_FX_GRID_PLANE_LINE_B "rgba(124, 255, 0, 0.24)"
#define VM_FX_GRID_GLOW_HEIGHT "63%"
#define VM_FX_GRID_GLOW_A "rgba(255, 43, 214, 0.26)"
#define VM_FX_GRID_GLOW_B "rgba(124, 255, 0, 0.1)"
#define VM_FX_GRID_HORIZON_BOTTOM "59%"
#define VM_FX_GRID_HORIZON_A "rgba(255, 43, 214, 0.5)"
#define VM_FX_GRID_HORIZON_B "rgba(124, 255, 0, 0.46)"
#define VM_FX_GRID_HORIZON_SHADOW_A "rgba(255, 43, 214, 0.24)"
#define VM_FX_GRID_HORIZON_SHADOW_B "rgba(124, 255, 0, 0.2)"
#define VM_FX_GRID_SCANLINE_A "rgba(44, 244, 255, 0.44)"
#define VM_FX_GRID_SCANLINE_SHADOW "rgba(255, 43, 214, 0.25)"
#define VM_FX_GRID_VLINE_A "rgba(255, 43, 214, 0.28)"
#define VM_FX_GRID_VLINE_B "rgba(124, 255, 0, 0.24)"
#define VM_FX_GRID_VIGNETTE "rgba(8, 4, 14, 0.66)"
#define VM_FX_GRID_SCROLL_DURATION "7.2s"
#define VM_FX_GRID_GLOW_DURATION "8.6s"
#define VM_FX_GRID_SCAN_DURATION "7.4s"
#define VM_FX_GRID_VLINE_DURATION "8.1s"
#define VM_LOGO_COLOR 0xF95A  /* #FF2BD6 */
#define VM_SELECT_OPTION_BG 0x28C9  /* #2B1A4A */
#define VM_SELECT_OPTION_COLOR 0xFFBF  /* #F9F4FF */
#define VM_SELECT_OPTION_HOVER_BG "rgba(124, 255, 0, 0.9)"
#define VM_SELECT_OPTION_HOVER_COLOR 0x10A1  /* #13140D */
#define VM_SELECT_OPTION_SELECTED_BG "rgba(255, 43, 214, 0.86)"
#define VM_SELECT_OPTION_SELECTED_COLOR 0xFFBF  /* #FFF5FC */

#endif /* VIBEMILK_ACID_POP_H */
