/* Vibemilk Design System v3.0.0 */
/* Theme: mint-protocol */
/* Auto-generated by build-tokens.js -- do not edit */
/* Colors are RGB565 for ESP32 TFT displays */

#ifndef VIBEMILK_MINT_PROTOCOL_H
#define VIBEMILK_MINT_PROTOCOL_H

#include <stdint.h>

#define VM_THEME_MODE "'light'"
#define VM_FONT_FAMILY "'Encode Sans Semi Expanded', 'Montserrat', -apple-system, BlinkMacSystemFont, sans-serif"
#define VM_FONT_MONO "'IBM Plex Mono', 'Space Mono', 'SF Mono', 'Fira Code', 'Cascadia Code', monospace"
#define VM_FONT_ICONS "'VibemilkIcons', 'Symbols Nerd Font Mono', sans-serif"
#define VM_FS_DISPLAY_XL 37
#define VM_FS_DISPLAY_LG 29
#define VM_FS_HEADING_XL 24
#define VM_FS_HEADING_LG 20
#define VM_FS_HEADING_MD 17
#define VM_FS_HEADING_SM 15
#define VM_FS_BODY_LG 15
#define VM_FS_BODY_MD 14
#define VM_FS_BODY_SM 12
#define VM_FS_CAPTION 11
#define VM_FS_OVERLINE 10
#define VM_FS_MICRO 9
#define VM_FW_LIGHT 400
#define VM_FW_REGULAR 400
#define VM_FW_MEDIUM 500
#define VM_FW_SEMIBOLD 500
#define VM_FW_BOLD 500
#define VM_FW_EXTRABOLD 500
#define VM_BTN_HEIGHT_XS 28
#define VM_BTN_HEIGHT_SM 36
#define VM_BTN_HEIGHT_MD 44
#define VM_BTN_HEIGHT_LG 52
#define VM_BTN_HEIGHT_XL 56
#define VM_BTN_PADDING_XS 10
#define VM_BTN_PADDING_SM 16
#define VM_BTN_PADDING_MD 22
#define VM_BTN_PADDING_LG 28
#define VM_BTN_PADDING_XL 32
#define VM_INPUT_HEIGHT_SM 40
#define VM_INPUT_HEIGHT_MD 46
#define VM_INPUT_HEIGHT_LG 54
#define VM_PROGRESS_HEIGHT 12
#define VM_TOGGLE_TRACK_WIDTH 44
#define VM_TOGGLE_TRACK_HEIGHT 24
#define VM_TOGGLE_THUMB_SIZE 18
#define VM_TOGGLE_THUMB_OFFSET 3
#define VM_AVATAR_SIZE_XS 28
#define VM_AVATAR_SIZE_SM 36
#define VM_AVATAR_SIZE_MD 44
#define VM_AVATAR_SIZE_LG 56
#define VM_AVATAR_SIZE_XL 72
#define VM_BG_DEEPEST 0xDF5B  /* #DBE8DB */
#define VM_BG_DEEP 0xE79C  /* #E7F0E7 */
#define VM_BG_SURFACE 0xF7DE  /* #F5F8F3 */
#define VM_BG_SURFACE_HOVER 0xEFBD  /* #EEF4ED */
#define VM_BG_ELEVATED 0xFFFF  /* #FFFFFF */
#define VM_BG_ELEVATED_HOVER 0xF7DE  /* #F7FBF7 */
#define VM_BG_INPUT 0xFFFF  /* #FFFFFF */
#define VM_BG_INPUT_FOCUS 0xFFDE  /* #F8FBF7 */
#define VM_BG_OVERLAY "rgba(219, 232, 219, 0.82)"
#define VM_TEXT_PRIMARY 0x1183  /* #15311B */
#define VM_TEXT_SECONDARY 0x2A05  /* #28432D */
#define VM_TEXT_TERTIARY 0x5C2B  /* #58855C */
#define VM_TEXT_MUTED 0x744E  /* #718A75 */
#define VM_TEXT_INVERSE 0xFFFF  /* #FBFDFC */
#define VM_TEXT_ON_GRADIENT 0x1183  /* #17311B */
#define VM_ACCENT_PRIMARY 0x5C2B  /* #58855C */
#define VM_ACCENT_PRIMARY_HOVER 0x6CCE  /* #6F9A72 */
#define VM_ACCENT_PRIMARY_ACTIVE 0x4349  /* #456A49 */
#define VM_ACCENT_PRIMARY_SUBTLE "rgba(88, 133, 92, 0.12)"
#define VM_ACCENT_SECONDARY 0xDF5B  /* #DBE8DB */
#define VM_ACCENT_SECONDARY_HOVER 0xCEF9  /* #CFDECF */
#define VM_ACCENT_SECONDARY_SUBTLE "rgba(219, 232, 219, 0.72)"
#define VM_COLOR_SUCCESS 0x5DED  /* #5DBE6A */
#define VM_COLOR_SUCCESS_HOVER 0x7670  /* #73CE80 */
#define VM_COLOR_SUCCESS_SUBTLE "rgba(93, 190, 106, 0.16)"
#define VM_COLOR_WARNING 0xDE53  /* #DDC89F */
#define VM_COLOR_WARNING_HOVER 0xE6B7  /* #E7D7B8 */
#define VM_COLOR_WARNING_SUBTLE "rgba(221, 200, 159, 0.2)"
#define VM_COLOR_DANGER 0xD517  /* #D7A3BA */
#define VM_COLOR_DANGER_HOVER 0xE5B9  /* #E2B7C8 */
#define VM_COLOR_DANGER_SUBTLE "rgba(215, 163, 186, 0.18)"
#define VM_COLOR_INFO 0xAD1B  /* #A9A2D9 */
#define VM_COLOR_INFO_SUBTLE "rgba(169, 162, 217, 0.18)"
#define VM_GRADIENT_BRAND "linear-gradient(135deg, #58855C 0%, #ADEBB3 100%)"
#define VM_GRADIENT_CARD "linear-gradient(135deg, #ADEBB3 0%, #A9A2D9 54%, #D7A3BA 100%)"
#define VM_GRADIENT_SUCCESS "linear-gradient(135deg, #ADEBB3 0%, #5DBE6A 100%)"
#define VM_GRADIENT_WARM "linear-gradient(135deg, #D7A3BA 0%, #DDC89F 100%)"
#define VM_GRADIENT_SURFACE "linear-gradient(160deg, #FBFDFC 0%, #DBE8DB 100%)"
#define VM_GRADIENT_SIDEBAR "linear-gradient(180deg, #ECF4EA 0%, #D3E0D3 100%)"
#define VM_GRADIENT_GLOW_PURPLE "radial-gradient(circle, rgba(215, 163, 186, 0.18) 0%, transparent 70%)"
#define VM_GRADIENT_GLOW_BLUE "radial-gradient(circle, rgba(169, 162, 217, 0.16) 0%, transparent 72%)"
#define VM_SPACE_0 0
#define VM_SPACE_1 4
#define VM_SPACE_2 8
#define VM_SPACE_3 12
#define VM_SPACE_4 16
#define VM_SPACE_5 20
#define VM_SPACE_6 24
#define VM_SPACE_8 32
#define VM_SPACE_10 40
#define VM_SPACE_12 48
#define VM_SPACE_16 64
#define VM_PHI_1 4
#define VM_PHI_2 7
#define VM_PHI_3 11
#define VM_PHI_4 18
#define VM_PHI_5 29
#define VM_PHI_6 47
#define VM_PHI_7 76
#define VM_PHI_8 123
#define VM_RADIUS_XS 6
#define VM_RADIUS_SM 10
#define VM_RADIUS_MD 14
#define VM_RADIUS_LG 18
#define VM_RADIUS_XL 24
#define VM_RADIUS_2XL 30
#define VM_RADIUS_FULL 9999
#define VM_SHADOW_SM "0 3px 10px rgba(21, 49, 27, 0.07)"
#define VM_SHADOW_MD "0 10px 22px rgba(21, 49, 27, 0.1)"
#define VM_SHADOW_LG "0 16px 34px rgba(21, 49, 27, 0.12)"
#define VM_SHADOW_XL "0 24px 46px rgba(21, 49, 27, 0.15)"
#define VM_SHADOW_GLOW_SM "0 0 18px rgba(173, 235, 179, 0.24)"
#define VM_SHADOW_GLOW_MD "0 0 28px rgba(215, 163, 186, 0.18)"
#define VM_SHADOW_GLOW_BLUE "0 0 24px rgba(169, 162, 217, 0.18)"
#define VM_SHADOW_INSET "inset 0 0 0 1px rgba(88, 133, 92, 0.08), inset 0 1px 4px rgba(21, 49, 27, 0.04)"
#define VM_STROKE_WIDTH_UI 1
#define VM_STROKE_WIDTH_STRONG 1
#define VM_STROKE_WIDTH_HEAVY 2
#define VM_STROKE_SUBTLE "rgba(88, 133, 92, 0.08)"
#define VM_STROKE_DEFAULT "rgba(88, 133, 92, 0.16)"
#define VM_STROKE_STRONG "rgba(88, 133, 92, 0.26)"
#define VM_STROKE_ACCENT 0x5C2B  /* #58855C */
#define VM_STROKE_SUCCESS 0x5DED  /* #5DBE6A */
#define VM_STROKE_DANGER 0xD517  /* #D7A3BA */
#define VM_BORDER_SUBTLE "var(--stroke-width-ui) solid var(--stroke-subtle)"
#define VM_BORDER_DEFAULT "var(--stroke-width-ui) solid var(--stroke-default)"
#define VM_BORDER_STRONG "var(--stroke-width-strong) solid var(--stroke-strong)"
#define VM_BORDER_ACCENT "var(--stroke-width-strong) solid var(--stroke-accent)"
#define VM_BORDER_SUCCESS "var(--stroke-width-strong) solid var(--stroke-success)"
#define VM_BORDER_DANGER "var(--stroke-width-strong) solid var(--stroke-danger)"
#define VM_TRANSITION_FAST "150ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_BASE "250ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_SLOW "400ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_SPRING "500ms cubic-bezier(0.34, 1.56, 0.64, 1)"
#define VM_Z_BASE 0
#define VM_Z_RAISED 10
#define VM_Z_DROPDOWN 100
#define VM_Z_STICKY 200
#define VM_Z_OVERLAY 300
#define VM_Z_MODAL 400
#define VM_Z_TOAST 500
#define VM_Z_TOOLTIP 600
#define VM_CONTAINER_SM 640
#define VM_CONTAINER_MD 960
#define VM_CONTAINER_LG 1200
#define VM_CONTAINER_XL 1440
#define VM_SIDEBAR_COLLAPSED 108
#define VM_SIDEBAR_EXPANDED 272
#define VM_TOPBAR_HEIGHT 72
#define VM_SELECTION_BG "rgba(173, 235, 179, 0.42)"
#define VM_SELECTION_TEXT 0x1183  /* #15311B */
#define VM_SURFACE_OVERLAY_SOFT "rgba(255, 255, 255, 0.68)"
#define VM_SURFACE_OVERLAY_STRONG "rgba(88, 133, 92, 0.14)"
#define VM_CARD_HOVER_BORDER "rgba(169, 162, 217, 0.3)"
#define VM_TABLE_STRIPE_BG "rgba(88, 133, 92, 0.03)"
#define VM_DIVIDER_COLOR "rgba(88, 133, 92, 0.12)"
#define VM_DIVIDER_DASHED_COLOR "rgba(169, 162, 217, 0.18)"
#define VM_SKELETON_SHIMMER "linear-gradient(90deg, transparent, rgba(88, 133, 92, 0.08), transparent)"
#define VM_FOCUS_RING_COLOR "rgba(88, 133, 92, 0.34)"
#define VM_FOCUS_RING_SOFT "0 0 0 3px rgba(88, 133, 92, 0.14)"
#define VM_FOCUS_RING_DANGER "0 0 0 3px rgba(215, 163, 186, 0.18)"
#define VM_SCROLLBAR_TRACK "color-mix(in srgb, var(--bg-deep) 82%, var(--text-primary) 18%)"
#define VM_SCROLLBAR_THUMB "color-mix(in srgb, var(--accent-primary) 54%, var(--text-primary) 46%)"
#define VM_SCROLLBAR_THUMB_HOVER "color-mix(in srgb, var(--accent-primary) 40%, var(--text-primary) 60%)"
#define VM_SCROLLBAR_CORNER "color-mix(in srgb, var(--bg-deep) 72%, var(--bg-elevated) 28%)"
#define VM_SCROLLBAR_DURATION "220ms cubic-bezier(0.22, 1, 0.36, 1)"
#define VM_GUI_PANEL_BG "color-mix(in srgb, var(--bg-elevated) 78%, var(--bg-surface) 22%)"
#define VM_GUI_PANEL_BORDER "1px solid color-mix(in srgb, var(--stroke-default) 70%, var(--text-primary) 30%)"
#define VM_GUI_PANEL_HEADER "color-mix(in srgb, var(--text-primary) 76%, var(--text-secondary) 24%)"
#define VM_GUI_PANEL_SHADOW "var(--shadow-md)"
#define VM_GUI_ROW_GAP "var(--space-4)"
#define VM_GUI_LABEL_COLOR "color-mix(in srgb, var(--text-secondary) 82%, var(--text-primary) 18%)"
#define VM_GUI_VALUE_COLOR "var(--text-primary)"
#define VM_GUI_VALUE_BORDER "1px solid color-mix(in srgb, var(--stroke-default) 74%, var(--text-primary) 26%)"
#define VM_GUI_SLIDER_TRACK "color-mix(in srgb, var(--bg-deep) 45%, var(--text-primary) 55%)"
#define VM_GUI_SLIDER_THUMB "color-mix(in srgb, var(--accent-primary) 68%, var(--text-primary) 32%)"
#define VM_GUI_SLIDER_THUMB_SHADOW "var(--range-thumb-shadow)"
#define VM_GUI_SLIDER_TRANSITION "220ms cubic-bezier(0.22, 1, 0.36, 1)"
#define VM_GRADIENT_TEXT "linear-gradient(90deg, #FF1DA5 0%, #A044C8 55%, #5D3FD3 100%)"
#define VM_TEXT_ON_PRIMARY 0xF7DE  /* #F7FBF7 */
#define VM_TEXT_ON_SUCCESS 0x1102  /* #112317 */
#define VM_TEXT_ON_DANGER 0x4926  /* #4B2436 */
#define VM_TEXT_ON_WARNING 0x3962  /* #3B2E14 */
#define VM_LOADER_STROKE "rgba(21, 49, 27, 0.12)"
#define VM_LOADER_STROKE_ACTIVE 0x5C2B  /* #58855C */
#define VM_CONTROL_HANDLE 0xFFFF  /* #FFFFFF */
#define VM_CONTROL_HANDLE_SHADOW "0 1px 4px rgba(21, 49, 27, 0.14)"
#define VM_RANGE_THUMB_SHADOW "0 1px 4px rgba(21, 49, 27, 0.16)"
#define VM_STATUS_GLOW_SUCCESS "0 0 10px rgba(93, 190, 106, 0.28)"
#define VM_STATUS_GLOW_WARNING "0 0 10px rgba(221, 200, 159, 0.26)"
#define VM_NERDS_BORDER "var(--stroke-width-ui) solid rgba(88, 133, 92, 0.12)"
#define VM_NERDS_INSET_GLOW "inset 0 0 48px rgba(173, 235, 179, 0.18)"
#define VM_NERDS_LABEL 0x6C2E  /* #6E8572 */
#define VM_NERDS_DIVIDER "rgba(169, 162, 217, 0.18)"
#define VM_NERDS_FOOTER_BORDER "var(--stroke-width-ui) solid rgba(88, 133, 92, 0.08)"
#define VM_NERDS_FOOTER_COLOR 0x6C2E  /* #6F8673 */
#define VM_FX_GRID_PERSPECTIVE 610
#define VM_FX_GRID_PLANE_BOTTOM "-7vh"
#define VM_FX_GRID_PLANE_HEIGHT "63vh"
#define VM_FX_GRID_PLANE_SIZE 35
#define VM_FX_GRID_PLANE_OPACITY "0.56"
#define VM_FX_GRID_PLANE_LINE_A "rgba(88, 133, 92, 0.1)"
#define VM_FX_GRID_PLANE_LINE_B "rgba(169, 162, 217, 0.1)"
#define VM_FX_GRID_GLOW_HEIGHT "63%"
#define VM_FX_GRID_GLOW_A "rgba(173, 235, 179, 0.18)"
#define VM_FX_GRID_GLOW_B "rgba(215, 163, 186, 0.08)"
#define VM_FX_GRID_HORIZON_BOTTOM "59%"
#define VM_FX_GRID_HORIZON_A "rgba(88, 133, 92, 0.2)"
#define VM_FX_GRID_HORIZON_B "rgba(169, 162, 217, 0.18)"
#define VM_FX_GRID_HORIZON_SHADOW_A "rgba(88, 133, 92, 0.12)"
#define VM_FX_GRID_HORIZON_SHADOW_B "rgba(169, 162, 217, 0.1)"
#define VM_FX_GRID_SCANLINE_A "rgba(215, 163, 186, 0.16)"
#define VM_FX_GRID_SCANLINE_SHADOW "rgba(215, 163, 186, 0.12)"
#define VM_FX_GRID_VLINE_A "rgba(88, 133, 92, 0.12)"
#define VM_FX_GRID_VLINE_B "rgba(169, 162, 217, 0.12)"
#define VM_FX_GRID_VIGNETTE "rgba(219, 232, 219, 0.28)"
#define VM_FX_GRID_SCROLL_DURATION "8.2s"
#define VM_FX_GRID_GLOW_DURATION "9.4s"
#define VM_FX_GRID_SCAN_DURATION "8.2s"
#define VM_FX_GRID_VLINE_DURATION "8.8s"
#define VM_LOGO_COLOR 0x5C2B  /* #58855C */
#define VM_SELECT_OPTION_BG 0xF7DE  /* #F6FAF6 */
#define VM_SELECT_OPTION_COLOR 0x19A4  /* #1C3420 */
#define VM_SELECT_OPTION_HOVER_BG "rgba(173, 235, 179, 0.7)"
#define VM_SELECT_OPTION_HOVER_COLOR 0x1183  /* #15311B */
#define VM_SELECT_OPTION_SELECTED_BG "rgba(169, 162, 217, 0.34)"
#define VM_SELECT_OPTION_SELECTED_COLOR 0x1907  /* #1B233C */
#define VM_COLOR_INFO_HOVER 0xBDBC  /* #BBB5E4 */

#endif /* VIBEMILK_MINT_PROTOCOL_H */
