/* Vibemilk Design System v3.0.0 */
/* Theme: mono-brutalist */
/* Auto-generated by build-tokens.js -- do not edit */
/* Colors are RGB565 for ESP32 TFT displays */

#ifndef VIBEMILK_MONO_BRUTALIST_H
#define VIBEMILK_MONO_BRUTALIST_H

#include <stdint.h>

#define VM_THEME_MODE "'dark'"
#define VM_FONT_FAMILY "'IBM Plex Mono', 'Space Mono', 'Montserrat', -apple-system, BlinkMacSystemFont, monospace"
#define VM_FONT_MONO "'IBM Plex Mono', 'Space Mono', 'SF Mono', 'Fira Code', 'Cascadia Code', monospace"
#define VM_FONT_ICONS "'VibemilkIcons', 'Symbols Nerd Font Mono', sans-serif"
#define VM_FS_DISPLAY_XL 36
#define VM_FS_DISPLAY_LG 28
#define VM_FS_HEADING_XL 23
#define VM_FS_HEADING_LG 19
#define VM_FS_HEADING_MD 17
#define VM_FS_HEADING_SM 15
#define VM_FS_BODY_LG 15
#define VM_FS_BODY_MD 14
#define VM_FS_BODY_SM 12
#define VM_FS_CAPTION 11
#define VM_FS_OVERLINE 10
#define VM_FS_MICRO 9
#define VM_FW_LIGHT 300
#define VM_FW_REGULAR 400
#define VM_FW_MEDIUM 500
#define VM_FW_SEMIBOLD 600
#define VM_FW_BOLD 700
#define VM_FW_EXTRABOLD 800
#define VM_BTN_HEIGHT_XS 28
#define VM_BTN_HEIGHT_SM 36
#define VM_BTN_HEIGHT_MD 44
#define VM_BTN_HEIGHT_LG 52
#define VM_BTN_HEIGHT_XL 56
#define VM_BTN_PADDING_XS 10
#define VM_BTN_PADDING_SM 16
#define VM_BTN_PADDING_MD 22
#define VM_BTN_PADDING_LG 28
#define VM_BTN_PADDING_XL 32
#define VM_INPUT_HEIGHT_SM 40
#define VM_INPUT_HEIGHT_MD 46
#define VM_INPUT_HEIGHT_LG 54
#define VM_PROGRESS_HEIGHT 12
#define VM_TOGGLE_TRACK_WIDTH 44
#define VM_TOGGLE_TRACK_HEIGHT 24
#define VM_TOGGLE_THUMB_SIZE 18
#define VM_TOGGLE_THUMB_OFFSET 3
#define VM_AVATAR_SIZE_XS 28
#define VM_AVATAR_SIZE_SM 36
#define VM_AVATAR_SIZE_MD 44
#define VM_AVATAR_SIZE_LG 56
#define VM_AVATAR_SIZE_XL 72
#define VM_BG_DEEPEST 0x0841  /* #0A0A0A */
#define VM_BG_DEEP 0x1082  /* #111111 */
#define VM_BG_SURFACE 0x18C3  /* #1A1A1A */
#define VM_BG_SURFACE_HOVER 0x2104  /* #232323 */
#define VM_BG_ELEVATED 0x2124  /* #242424 */
#define VM_BG_ELEVATED_HOVER 0x2965  /* #2F2F2F */
#define VM_BG_INPUT 0x1082  /* #131313 */
#define VM_BG_INPUT_FOCUS 0x18E3  /* #1D1D1D */
#define VM_BG_OVERLAY "rgba(8, 8, 8, 0.9)"
#define VM_TEXT_PRIMARY 0xF79E  /* #F3F3F3 */
#define VM_TEXT_SECONDARY 0xCE79  /* #CFCFCF */
#define VM_TEXT_TERTIARY 0x8C71  /* #8F8F8F */
#define VM_TEXT_MUTED 0x632C  /* #676767 */
#define VM_TEXT_INVERSE 0x1082  /* #111111 */
#define VM_TEXT_ON_GRADIENT 0x1082  /* #111111 */
#define VM_ACCENT_PRIMARY 0xF79E  /* #F1F1F1 */
#define VM_ACCENT_PRIMARY_HOVER 0xFFFF  /* #FFFFFF */
#define VM_ACCENT_PRIMARY_ACTIVE 0xD6BA  /* #D5D5D5 */
#define VM_ACCENT_PRIMARY_SUBTLE "rgba(255, 255, 255, 0.12)"
#define VM_ACCENT_SECONDARY 0xF9C6  /* #FF3B30 */
#define VM_ACCENT_SECONDARY_HOVER 0xFB4C  /* #FF6B63 */
#define VM_ACCENT_SECONDARY_SUBTLE "rgba(255, 59, 48, 0.18)"
#define VM_COLOR_SUCCESS 0xAF55  /* #AEE8AE */
#define VM_COLOR_SUCCESS_HOVER 0xCF99  /* #C9F1C9 */
#define VM_COLOR_SUCCESS_SUBTLE "rgba(174, 232, 174, 0.14)"
#define VM_COLOR_WARNING 0xFE8E  /* #FFD070 */
#define VM_COLOR_WARNING_HOVER 0xFEF3  /* #FFDE98 */
#define VM_COLOR_WARNING_SUBTLE "rgba(255, 208, 112, 0.16)"
#define VM_COLOR_DANGER 0xF9C6  /* #FF3B30 */
#define VM_COLOR_DANGER_HOVER 0xFB4C  /* #FF6B63 */
#define VM_COLOR_DANGER_SUBTLE "rgba(255, 59, 48, 0.18)"
#define VM_COLOR_INFO 0xEF5D  /* #EAEAEA */
#define VM_COLOR_INFO_SUBTLE "rgba(234, 234, 234, 0.14)"
#define VM_GRADIENT_BRAND 0xF9C6  /* #FF3B30 */
#define VM_GRADIENT_CARD 0x18C3  /* #1A1A1A */
#define VM_GRADIENT_SUCCESS 0xAF55  /* #AEE8AE */
#define VM_GRADIENT_WARM 0xFE8E  /* #FFD070 */
#define VM_GRADIENT_SURFACE 0x18C3  /* #1A1A1A */
#define VM_GRADIENT_SIDEBAR 0x1082  /* #111111 */
#define VM_GRADIENT_GLOW_PURPLE "none"
#define VM_GRADIENT_GLOW_BLUE "none"
#define VM_SPACE_0 0
#define VM_SPACE_1 4
#define VM_SPACE_2 8
#define VM_SPACE_3 12
#define VM_SPACE_4 16
#define VM_SPACE_5 20
#define VM_SPACE_6 24
#define VM_SPACE_8 32
#define VM_SPACE_10 40
#define VM_SPACE_12 48
#define VM_SPACE_16 64
#define VM_PHI_1 4
#define VM_PHI_2 7
#define VM_PHI_3 11
#define VM_PHI_4 18
#define VM_PHI_5 29
#define VM_PHI_6 47
#define VM_PHI_7 76
#define VM_PHI_8 123
#define VM_RADIUS_XS 0
#define VM_RADIUS_SM 0
#define VM_RADIUS_MD 0
#define VM_RADIUS_LG 0
#define VM_RADIUS_XL 0
#define VM_RADIUS_2XL 0
#define VM_RADIUS_FULL 0
#define VM_SHADOW_SM "3px 3px 0 rgba(0, 0, 0, 0.44)"
#define VM_SHADOW_MD "5px 5px 0 rgba(0, 0, 0, 0.5)"
#define VM_SHADOW_LG "8px 8px 0 rgba(0, 0, 0, 0.56)"
#define VM_SHADOW_XL "12px 12px 0 rgba(0, 0, 0, 0.6)"
#define VM_SHADOW_GLOW_SM "0 0 0 1px rgba(255, 255, 255, 0.2)"
#define VM_SHADOW_GLOW_MD "0 0 0 1px rgba(255, 59, 48, 0.34)"
#define VM_SHADOW_GLOW_BLUE "0 0 0 1px rgba(255, 59, 48, 0.42)"
#define VM_SHADOW_INSET "inset 0 0 0 1px rgba(255, 255, 255, 0.1), inset 0 -2px 0 rgba(255, 255, 255, 0.04)"
#define VM_STROKE_WIDTH_UI 2
#define VM_STROKE_WIDTH_STRONG 3
#define VM_STROKE_WIDTH_HEAVY 3
#define VM_STROKE_SUBTLE "rgba(255, 255, 255, 0.16)"
#define VM_STROKE_DEFAULT "rgba(255, 255, 255, 0.28)"
#define VM_STROKE_STRONG "rgba(255, 255, 255, 0.46)"
#define VM_STROKE_ACCENT 0xF79E  /* #F1F1F1 */
#define VM_STROKE_SUCCESS 0xAF55  /* #AEE8AE */
#define VM_STROKE_DANGER 0xF9C6  /* #FF3B30 */
#define VM_BORDER_SUBTLE "var(--stroke-width-ui) solid var(--stroke-subtle)"
#define VM_BORDER_DEFAULT "var(--stroke-width-ui) solid var(--stroke-default)"
#define VM_BORDER_STRONG "var(--stroke-width-strong) solid var(--stroke-strong)"
#define VM_BORDER_ACCENT "var(--stroke-width-strong) solid var(--stroke-accent)"
#define VM_BORDER_SUCCESS "var(--stroke-width-strong) solid var(--stroke-success)"
#define VM_BORDER_DANGER "var(--stroke-width-strong) solid var(--stroke-danger)"
#define VM_TRANSITION_FAST "150ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_BASE "250ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_SLOW "400ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_SPRING "500ms cubic-bezier(0.34, 1.56, 0.64, 1)"
#define VM_Z_BASE 0
#define VM_Z_RAISED 10
#define VM_Z_DROPDOWN 100
#define VM_Z_STICKY 200
#define VM_Z_OVERLAY 300
#define VM_Z_MODAL 400
#define VM_Z_TOAST 500
#define VM_Z_TOOLTIP 600
#define VM_CONTAINER_SM 640
#define VM_CONTAINER_MD 960
#define VM_CONTAINER_LG 1200
#define VM_CONTAINER_XL 1440
#define VM_SIDEBAR_COLLAPSED 108
#define VM_SIDEBAR_EXPANDED 272
#define VM_TOPBAR_HEIGHT 72
#define VM_SELECTION_BG "rgba(255, 59, 48, 0.4)"
#define VM_SELECTION_TEXT 0xFFFF  /* #FFFFFF */
#define VM_SURFACE_OVERLAY_SOFT "rgba(255, 255, 255, 0.06)"
#define VM_SURFACE_OVERLAY_STRONG "rgba(255, 59, 48, 0.2)"
#define VM_CARD_HOVER_BORDER "rgba(255, 59, 48, 0.54)"
#define VM_TABLE_STRIPE_BG "rgba(255, 255, 255, 0.03)"
#define VM_DIVIDER_COLOR "rgba(255, 255, 255, 0.22)"
#define VM_DIVIDER_DASHED_COLOR "rgba(255, 255, 255, 0.32)"
#define VM_SKELETON_SHIMMER "rgba(255, 255, 255, 0.13)"
#define VM_FOCUS_RING_COLOR "rgba(255, 59, 48, 0.58)"
#define VM_FOCUS_RING_SOFT "0 0 0 3px rgba(255, 59, 48, 0.22)"
#define VM_FOCUS_RING_DANGER "0 0 0 3px rgba(255, 59, 48, 0.28)"
#define VM_SCROLLBAR_TRACK "color-mix(in srgb, var(--bg-deep) 82%, var(--text-primary) 18%)"
#define VM_SCROLLBAR_THUMB "color-mix(in srgb, var(--accent-primary) 54%, var(--text-primary) 46%)"
#define VM_SCROLLBAR_THUMB_HOVER "color-mix(in srgb, var(--accent-primary) 40%, var(--text-primary) 60%)"
#define VM_SCROLLBAR_CORNER "color-mix(in srgb, var(--bg-deep) 72%, var(--bg-elevated) 28%)"
#define VM_SCROLLBAR_DURATION "220ms cubic-bezier(0.22, 1, 0.36, 1)"
#define VM_GUI_PANEL_BG "color-mix(in srgb, var(--bg-elevated) 78%, var(--bg-surface) 22%)"
#define VM_GUI_PANEL_BORDER "1px solid color-mix(in srgb, var(--stroke-default) 70%, var(--text-primary) 30%)"
#define VM_GUI_PANEL_HEADER "color-mix(in srgb, var(--text-primary) 76%, var(--text-secondary) 24%)"
#define VM_GUI_PANEL_SHADOW "var(--shadow-md)"
#define VM_GUI_ROW_GAP "var(--space-4)"
#define VM_GUI_LABEL_COLOR "color-mix(in srgb, var(--text-secondary) 82%, var(--text-primary) 18%)"
#define VM_GUI_VALUE_COLOR "var(--text-primary)"
#define VM_GUI_VALUE_BORDER "1px solid color-mix(in srgb, var(--stroke-default) 74%, var(--text-primary) 26%)"
#define VM_GUI_SLIDER_TRACK "color-mix(in srgb, var(--bg-deep) 45%, var(--text-primary) 55%)"
#define VM_GUI_SLIDER_THUMB "color-mix(in srgb, var(--accent-primary) 68%, var(--text-primary) 32%)"
#define VM_GUI_SLIDER_THUMB_SHADOW "var(--range-thumb-shadow)"
#define VM_GUI_SLIDER_TRANSITION "220ms cubic-bezier(0.22, 1, 0.36, 1)"
#define VM_GRADIENT_TEXT "linear-gradient(90deg, #FF1DA5 0%, #A044C8 55%, #5D3FD3 100%)"
#define VM_TEXT_ON_PRIMARY 0x1082  /* #111111 */
#define VM_TEXT_ON_SUCCESS 0x18C3  /* #1B1B1B */
#define VM_TEXT_ON_DANGER 0xFFBE  /* #FFF4F4 */
#define VM_TEXT_ON_WARNING 0x2901  /* #2A220F */
#define VM_LOADER_STROKE "rgba(243, 243, 243, 0.26)"
#define VM_LOADER_STROKE_ACTIVE 0xF79E  /* #F3F3F3 */
#define VM_CONTROL_HANDLE 0xF79E  /* #F3F3F3 */
#define VM_CONTROL_HANDLE_SHADOW "0 2px 0 rgba(0, 0, 0, 0.38)"
#define VM_RANGE_THUMB_SHADOW "0 2px 0 rgba(0, 0, 0, 0.42)"
#define VM_STATUS_GLOW_SUCCESS "0 0 0 1px rgba(174, 232, 174, 0.46)"
#define VM_STATUS_GLOW_WARNING "0 0 0 1px rgba(255, 208, 112, 0.52)"
#define VM_NERDS_BORDER "var(--stroke-width-ui) solid rgba(255, 255, 255, 0.2)"
#define VM_NERDS_INSET_GLOW "inset 0 0 0 1px rgba(255, 255, 255, 0.08)"
#define VM_NERDS_LABEL 0xA534  /* #A6A6A6 */
#define VM_NERDS_DIVIDER "rgba(255, 255, 255, 0.2)"
#define VM_NERDS_FOOTER_BORDER "var(--stroke-width-ui) solid rgba(255, 255, 255, 0.16)"
#define VM_NERDS_FOOTER_COLOR 0x9CD3  /* #9A9A9A */
#define VM_FX_GRID_PERSPECTIVE 560
#define VM_FX_GRID_PLANE_BOTTOM "-7vh"
#define VM_FX_GRID_PLANE_HEIGHT "63vh"
#define VM_FX_GRID_PLANE_SIZE 36
#define VM_FX_GRID_PLANE_OPACITY 0
#define VM_FX_GRID_PLANE_LINE_A "transparent"
#define VM_FX_GRID_PLANE_LINE_B "transparent"
#define VM_FX_GRID_GLOW_HEIGHT "61%"
#define VM_FX_GRID_GLOW_A "transparent"
#define VM_FX_GRID_GLOW_B "transparent"
#define VM_FX_GRID_HORIZON_BOTTOM "58%"
#define VM_FX_GRID_HORIZON_A "transparent"
#define VM_FX_GRID_HORIZON_B "transparent"
#define VM_FX_GRID_HORIZON_SHADOW_A "transparent"
#define VM_FX_GRID_HORIZON_SHADOW_B "transparent"
#define VM_FX_GRID_SCANLINE_A "transparent"
#define VM_FX_GRID_SCANLINE_SHADOW "transparent"
#define VM_FX_GRID_VLINE_A "transparent"
#define VM_FX_GRID_VLINE_B "transparent"
#define VM_FX_GRID_VIGNETTE "transparent"
#define VM_FX_GRID_SCROLL_DURATION "8.6s"
#define VM_FX_GRID_GLOW_DURATION "9.2s"
#define VM_FX_GRID_SCAN_DURATION "8.4s"
#define VM_FX_GRID_VLINE_DURATION "8.8s"
#define VM_LOGO_COLOR 0xFFFF  /* #FFFFFF */
#define VM_SELECT_OPTION_BG 0x18C3  /* #1A1A1A */
#define VM_SELECT_OPTION_COLOR 0xF79E  /* #F3F3F3 */
#define VM_SELECT_OPTION_HOVER_BG 0x2965  /* #2D2D2D */
#define VM_SELECT_OPTION_HOVER_COLOR 0xFFFF  /* #FFFFFF */
#define VM_SELECT_OPTION_SELECTED_BG 0xF9C6  /* #FF3B30 */
#define VM_SELECT_OPTION_SELECTED_COLOR 0xFFFF  /* #FFFFFF */

#endif /* VIBEMILK_MONO_BRUTALIST_H */
