/* Vibemilk Design System v3.0.0 */
/* Theme: vibemilk-default */
/* Auto-generated by build-tokens.js -- do not edit */
/* Colors are RGB565 for ESP32 TFT displays */

#ifndef VIBEMILK_VIBEMILK_DEFAULT_H
#define VIBEMILK_VIBEMILK_DEFAULT_H

#include <stdint.h>

#define VM_THEME_MODE "'light'"
#define VM_FONT_FAMILY "'Matt', -apple-system, BlinkMacSystemFont, sans-serif"
#define VM_FONT_MONO "'Space Mono', 'SF Mono', 'Fira Code', 'Cascadia Code', monospace"
#define VM_FONT_ICONS "'VibemilkIcons', 'Symbols Nerd Font Mono', sans-serif"
#define VM_FS_DISPLAY_XL 36
#define VM_FS_DISPLAY_LG 28
#define VM_FS_HEADING_XL 24
#define VM_FS_HEADING_LG 20
#define VM_FS_HEADING_MD 18
#define VM_FS_HEADING_SM 16
#define VM_FS_BODY_LG 16
#define VM_FS_BODY_MD 14
#define VM_FS_BODY_SM 13
#define VM_FS_CAPTION 12
#define VM_FS_OVERLINE 11
#define VM_FS_MICRO 10
#define VM_FW_LIGHT 300
#define VM_FW_REGULAR 400
#define VM_FW_MEDIUM 500
#define VM_FW_SEMIBOLD 600
#define VM_FW_BOLD 700
#define VM_FW_EXTRABOLD 800
#define VM_BTN_HEIGHT_XS 28
#define VM_BTN_HEIGHT_SM 34
#define VM_BTN_HEIGHT_MD 40
#define VM_BTN_HEIGHT_LG 48
#define VM_BTN_HEIGHT_XL 56
#define VM_BTN_PADDING_XS 10
#define VM_BTN_PADDING_SM 14
#define VM_BTN_PADDING_MD 18
#define VM_BTN_PADDING_LG 24
#define VM_BTN_PADDING_XL 32
#define VM_INPUT_HEIGHT_SM 38
#define VM_INPUT_HEIGHT_MD 44
#define VM_INPUT_HEIGHT_LG 52
#define VM_PROGRESS_HEIGHT 12
#define VM_TOGGLE_TRACK_WIDTH 44
#define VM_TOGGLE_TRACK_HEIGHT 24
#define VM_TOGGLE_THUMB_SIZE 18
#define VM_TOGGLE_THUMB_OFFSET 3
#define VM_AVATAR_SIZE_XS 28
#define VM_AVATAR_SIZE_SM 36
#define VM_AVATAR_SIZE_MD 44
#define VM_AVATAR_SIZE_LG 56
#define VM_AVATAR_SIZE_XL 72
#define VM_BG_DEEPEST 0xF77D  /* #F0EDE8 */
#define VM_BG_DEEP 0xF79D  /* #F5F2ED */
#define VM_BG_SURFACE 0xFFDE  /* #FAF8F5 */
#define VM_BG_SURFACE_HOVER 0xF77D  /* #F0EDE8 */
#define VM_BG_ELEVATED 0xFFFF  /* #FFFFFF */
#define VM_BG_ELEVATED_HOVER 0xF79D  /* #F5F2ED */
#define VM_BG_INPUT 0xFFFF  /* #FFFFFF */
#define VM_BG_INPUT_FOCUS 0xFFFF  /* #FFFFFF */
#define VM_BG_OVERLAY "rgba(35, 83, 138, 0.75)"
#define VM_TEXT_PRIMARY 0x18C5  /* #1A1A2E */
#define VM_TEXT_SECONDARY 0x4A4D  /* #4A4A6A */
#define VM_TEXT_TERTIARY 0x6B71  /* #6E6E8A */
#define VM_TEXT_MUTED 0x9CF6  /* #9E9EB5 */
#define VM_TEXT_INVERSE 0xFFFF  /* #FFFFFF */
#define VM_TEXT_ON_GRADIENT 0xFFFF  /* #FFFFFF */
#define VM_ACCENT_PRIMARY 0xF8F4  /* #FF1DA5 */
#define VM_ACCENT_PRIMARY_HOVER 0xFA37  /* #FF45B8 */
#define VM_ACCENT_PRIMARY_ACTIVE 0xE0D1  /* #E0188F */
#define VM_ACCENT_PRIMARY_SUBTLE "rgba(255, 29, 165, 0.10)"
#define VM_ACCENT_SECONDARY 0x5C3B  /* #5D84DF */
#define VM_ACCENT_SECONDARY_HOVER 0x7CDD  /* #7A9BE8 */
#define VM_ACCENT_SECONDARY_SUBTLE "rgba(93, 132, 223, 0.10)"
#define VM_COLOR_SUCCESS 0x05AE  /* #01B574 */
#define VM_COLOR_SUCCESS_HOVER 0x06B1  /* #02D68A */
#define VM_COLOR_SUCCESS_SUBTLE "rgba(1, 181, 116, 0.12)"
#define VM_COLOR_WARNING 0xFDA8  /* #FFB547 */
#define VM_COLOR_WARNING_HOVER 0xFE2D  /* #FFC76B */
#define VM_COLOR_WARNING_SUBTLE "rgba(255, 181, 71, 0.12)"
#define VM_COLOR_DANGER 0xEAEA  /* #EE5D50 */
#define VM_COLOR_DANGER_HOVER 0xF3CE  /* #F17A70 */
#define VM_COLOR_DANGER_SUBTLE "rgba(238, 93, 80, 0.12)"
#define VM_COLOR_INFO 0x3DDF  /* #39B8FF */
#define VM_COLOR_INFO_SUBTLE "rgba(57, 184, 255, 0.12)"
#define VM_GRADIENT_BRAND "linear-gradient(135deg, #FF1DA5 0%, #A044C8 50%, #5D3FD3 100%)"
#define VM_GRADIENT_CARD "linear-gradient(135deg, #FF1DA5 0%, #8B3FBF 55%, #5D3FD3 100%)"
#define VM_GRADIENT_SUCCESS "linear-gradient(135deg, #01B574 0%, #5D84DF 100%)"
#define VM_GRADIENT_WARM "linear-gradient(135deg, #FFB547 0%, #EE5D50 100%)"
#define VM_GRADIENT_SURFACE "linear-gradient(135deg, #FAF8F5 0%, #F0EDE8 100%)"
#define VM_GRADIENT_SIDEBAR "linear-gradient(180deg, #FAF8F5 0%, #F5F2ED 100%)"
#define VM_GRADIENT_GLOW_PURPLE "radial-gradient(circle, rgba(255,29,165,0.15) 0%, transparent 70%)"
#define VM_GRADIENT_GLOW_BLUE "radial-gradient(circle, rgba(93,132,223,0.12) 0%, transparent 70%)"
#define VM_SPACE_0 0
#define VM_SPACE_1 4
#define VM_SPACE_2 8
#define VM_SPACE_3 12
#define VM_SPACE_4 16
#define VM_SPACE_5 20
#define VM_SPACE_6 24
#define VM_SPACE_8 32
#define VM_SPACE_10 40
#define VM_SPACE_12 48
#define VM_SPACE_16 64
#define VM_PHI_1 4
#define VM_PHI_2 7
#define VM_PHI_3 11
#define VM_PHI_4 18
#define VM_PHI_5 29
#define VM_PHI_6 47
#define VM_PHI_7 76
#define VM_PHI_8 123
#define VM_RADIUS_XS 4
#define VM_RADIUS_SM 8
#define VM_RADIUS_MD 12
#define VM_RADIUS_LG 16
#define VM_RADIUS_XL 20
#define VM_RADIUS_2XL 24
#define VM_RADIUS_FULL 9999
#define VM_SHADOW_SM "0 2px 8px rgba(0, 0, 0, 0.06)"
#define VM_SHADOW_MD "0 4px 16px rgba(0, 0, 0, 0.08)"
#define VM_SHADOW_LG "0 8px 32px rgba(0, 0, 0, 0.10)"
#define VM_SHADOW_XL "0 16px 48px rgba(0, 0, 0, 0.12)"
#define VM_SHADOW_GLOW_SM "0 0 20px rgba(255, 29, 165, 0.10)"
#define VM_SHADOW_GLOW_MD "0 0 40px rgba(255, 29, 165, 0.12)"
#define VM_SHADOW_GLOW_BLUE "0 0 30px rgba(93, 132, 223, 0.10)"
#define VM_SHADOW_INSET "inset 0 2px 4px rgba(0, 0, 0, 0.04)"
#define VM_STROKE_WIDTH_UI 1
#define VM_STROKE_WIDTH_STRONG 1
#define VM_STROKE_WIDTH_HEAVY 2
#define VM_STROKE_SUBTLE "rgba(0, 0, 0, 0.06)"
#define VM_STROKE_DEFAULT "rgba(0, 0, 0, 0.10)"
#define VM_STROKE_STRONG "rgba(0, 0, 0, 0.18)"
#define VM_STROKE_ACCENT 0xF8F4  /* #FF1DA5 */
#define VM_STROKE_SUCCESS 0x05AE  /* #01B574 */
#define VM_STROKE_DANGER 0xEAEA  /* #EE5D50 */
#define VM_BORDER_SUBTLE "var(--stroke-width-ui) solid var(--stroke-subtle)"
#define VM_BORDER_DEFAULT "var(--stroke-width-ui) solid var(--stroke-default)"
#define VM_BORDER_STRONG "var(--stroke-width-strong) solid var(--stroke-strong)"
#define VM_BORDER_ACCENT "var(--stroke-width-strong) solid var(--stroke-accent)"
#define VM_BORDER_SUCCESS "var(--stroke-width-strong) solid var(--stroke-success)"
#define VM_BORDER_DANGER "var(--stroke-width-strong) solid var(--stroke-danger)"
#define VM_TRANSITION_FAST "150ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_BASE "250ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_SLOW "400ms cubic-bezier(0.4, 0, 0.2, 1)"
#define VM_TRANSITION_SPRING "500ms cubic-bezier(0.34, 1.56, 0.64, 1)"
#define VM_Z_BASE 0
#define VM_Z_RAISED 10
#define VM_Z_DROPDOWN 100
#define VM_Z_STICKY 200
#define VM_Z_OVERLAY 300
#define VM_Z_MODAL 400
#define VM_Z_TOAST 500
#define VM_Z_TOOLTIP 600
#define VM_CONTAINER_SM 640
#define VM_CONTAINER_MD 960
#define VM_CONTAINER_LG 1200
#define VM_CONTAINER_XL 1440
#define VM_SIDEBAR_COLLAPSED 100
#define VM_SIDEBAR_EXPANDED 260
#define VM_TOPBAR_HEIGHT 72
#define VM_SELECTION_BG "rgba(255, 29, 165, 0.20)"
#define VM_SELECTION_TEXT 0x18C5  /* #1A1A2E */
#define VM_SURFACE_OVERLAY_SOFT "rgba(0, 0, 0, 0.02)"
#define VM_SURFACE_OVERLAY_STRONG "rgba(0, 0, 0, 0.06)"
#define VM_CARD_HOVER_BORDER "rgba(0, 0, 0, 0.08)"
#define VM_TABLE_STRIPE_BG "rgba(0, 0, 0, 0.02)"
#define VM_DIVIDER_COLOR "rgba(0, 0, 0, 0.06)"
#define VM_DIVIDER_DASHED_COLOR "rgba(0, 0, 0, 0.10)"
#define VM_SKELETON_SHIMMER "linear-gradient(90deg, transparent, rgba(0, 0, 0, 0.03), transparent)"
#define VM_FOCUS_RING_COLOR "rgba(255, 29, 165, 0.4)"
#define VM_FOCUS_RING_SOFT "0 0 0 3px rgba(255, 29, 165, 0.12)"
#define VM_FOCUS_RING_DANGER "0 0 0 3px rgba(238, 93, 80, 0.15)"
#define VM_SCROLLBAR_TRACK "color-mix(in srgb, var(--bg-deep) 82%, var(--text-primary) 18%)"
#define VM_SCROLLBAR_THUMB "color-mix(in srgb, var(--accent-primary) 54%, var(--text-primary) 46%)"
#define VM_SCROLLBAR_THUMB_HOVER "color-mix(in srgb, var(--accent-primary) 40%, var(--text-primary) 60%)"
#define VM_SCROLLBAR_CORNER "color-mix(in srgb, var(--bg-deep) 72%, var(--bg-elevated) 28%)"
#define VM_SCROLLBAR_DURATION "220ms cubic-bezier(0.22, 1, 0.36, 1)"
#define VM_GUI_PANEL_BG "color-mix(in srgb, var(--bg-elevated) 78%, var(--bg-surface) 22%)"
#define VM_GUI_PANEL_BORDER "1px solid color-mix(in srgb, var(--stroke-default) 70%, var(--text-primary) 30%)"
#define VM_GUI_PANEL_HEADER "color-mix(in srgb, var(--text-primary) 76%, var(--text-secondary) 24%)"
#define VM_GUI_PANEL_SHADOW "var(--shadow-md)"
#define VM_GUI_ROW_GAP "var(--space-4)"
#define VM_GUI_LABEL_COLOR "color-mix(in srgb, var(--text-secondary) 82%, var(--text-primary) 18%)"
#define VM_GUI_VALUE_COLOR "var(--text-primary)"
#define VM_GUI_VALUE_BORDER "1px solid color-mix(in srgb, var(--stroke-default) 74%, var(--text-primary) 26%)"
#define VM_GUI_SLIDER_TRACK "color-mix(in srgb, var(--bg-deep) 45%, var(--text-primary) 55%)"
#define VM_GUI_SLIDER_THUMB "color-mix(in srgb, var(--accent-primary) 68%, var(--text-primary) 32%)"
#define VM_GUI_SLIDER_THUMB_SHADOW "var(--range-thumb-shadow)"
#define VM_GUI_SLIDER_TRANSITION "220ms cubic-bezier(0.22, 1, 0.36, 1)"
#define VM_GRADIENT_TEXT "linear-gradient(90deg, #FF1DA5 0%, #A044C8 55%, #5D3FD3 100%)"
#define VM_TEXT_ON_PRIMARY 0xFFFF  /* #FFFFFF */
#define VM_TEXT_ON_SUCCESS 0xFFFF  /* #FFFFFF */
#define VM_TEXT_ON_DANGER 0xFFFF  /* #FFFFFF */
#define VM_TEXT_ON_WARNING "var(--text-inverse)"
#define VM_LOADER_STROKE "rgba(255, 255, 255, 0.3)"
#define VM_LOADER_STROKE_ACTIVE 0xFFFF  /* #FFFFFF */
#define VM_CONTROL_HANDLE 0xFFFF  /* #FFFFFF */
#define VM_CONTROL_HANDLE_SHADOW "0 1px 3px rgba(0, 0, 0, 0.3)"
#define VM_RANGE_THUMB_SHADOW "0 1px 4px rgba(0, 0, 0, 0.3)"
#define VM_STATUS_GLOW_SUCCESS "0 0 8px rgba(1, 181, 116, 0.5)"
#define VM_STATUS_GLOW_WARNING "0 0 8px rgba(255, 181, 71, 0.5)"
#define VM_NERDS_BORDER "1px solid rgba(117, 81, 255, 0.15)"
#define VM_NERDS_INSET_GLOW "inset 0 0 60px rgba(117, 81, 255, 0.03)"
#define VM_NERDS_LABEL 0x4AAD  /* #4A5568 */
#define VM_NERDS_DIVIDER "rgba(112, 126, 174, 0.2)"
#define VM_NERDS_FOOTER_BORDER "1px solid rgba(112, 126, 174, 0.1)"
#define VM_NERDS_FOOTER_COLOR 0x4AAD  /* #4A5568 */
#define VM_FX_GRID_PERSPECTIVE 600
#define VM_FX_GRID_PLANE_BOTTOM "-8vh"
#define VM_FX_GRID_PLANE_HEIGHT "62vh"
#define VM_FX_GRID_PLANE_SIZE 36
#define VM_FX_GRID_PLANE_OPACITY "0.95"
#define VM_FX_GRID_PLANE_LINE_A "rgba(117, 81, 255, 0.2)"
#define VM_FX_GRID_PLANE_LINE_B "rgba(57, 184, 255, 0.18)"
#define VM_FX_GRID_GLOW_HEIGHT "62%"
#define VM_FX_GRID_GLOW_A "rgba(117, 81, 255, 0.18)"
#define VM_FX_GRID_GLOW_B "rgba(57, 184, 255, 0.08)"
#define VM_FX_GRID_HORIZON_BOTTOM "60%"
#define VM_FX_GRID_HORIZON_A "rgba(117, 81, 255, 0.4)"
#define VM_FX_GRID_HORIZON_B "rgba(57, 184, 255, 0.34)"
#define VM_FX_GRID_HORIZON_SHADOW_A "rgba(117, 81, 255, 0.24)"
#define VM_FX_GRID_HORIZON_SHADOW_B "rgba(57, 184, 255, 0.1)"
#define VM_FX_GRID_SCANLINE_A "rgba(57, 184, 255, 0.32)"
#define VM_FX_GRID_SCANLINE_SHADOW "rgba(57, 184, 255, 0.18)"
#define VM_FX_GRID_VLINE_A "rgba(117, 81, 255, 0.2)"
#define VM_FX_GRID_VLINE_B "rgba(57, 184, 255, 0.18)"
#define VM_FX_GRID_VIGNETTE "rgba(7, 13, 45, 0.54)"
#define VM_FX_GRID_SCROLL_DURATION "5s"
#define VM_FX_GRID_GLOW_DURATION "6s"
#define VM_FX_GRID_SCAN_DURATION "4s"
#define VM_FX_GRID_VLINE_DURATION "5s"
#define VM_LOGO_COLOR 0x18C5  /* #1A1A2E */
#define VM_SELECT_OPTION_BG "var(--bg-surface)"
#define VM_SELECT_OPTION_COLOR "var(--text-primary)"
#define VM_SELECT_OPTION_HOVER_BG "var(--bg-surface-hover)"
#define VM_SELECT_OPTION_HOVER_COLOR "var(--text-primary)"
#define VM_SELECT_OPTION_SELECTED_BG "var(--accent-primary-subtle)"
#define VM_SELECT_OPTION_SELECTED_COLOR "var(--accent-primary)"

#endif /* VIBEMILK_VIBEMILK_DEFAULT_H */
